//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBapi1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public int idusuario { get; set; }
        public string usuarionombre { get; set; }
        public string usuarioapellido { get; set; }
        public string usuariocorreo { get; set; }
        public string usuariodepartamento { get; set; }
        public string usuariotipo { get; set; }
    }
}
